In [1]:
import re
import pandas as pd
import fasttext

In [2]:
df = pd.read_csv("Indian_Food_Dataset.csv")

In [3]:
df

,TranslatedRecipeName,TranslatedIngredients,TotalTimeInMins,Cuisine,TranslatedInstructions,URL,Cleaned-Ingredients,image-url,Ingredient-count
0,Masala Karela Recipe,"1 tablespoon Red Chilli powder,3 tablespoon Gr...",45,Indian,"To begin making the Masala Karela Recipe,de-se...",https://www.archanaskitchen.com/masala-karela-...,"salt,amchur (dry mango powder),karela (bitter ...",https://www.archanaskitchen.com/images/archana...,10
1,Spicy Tomato Rice (Recipe),"2 teaspoon cashew - or peanuts, 1/2 Teaspoon ...",15,South Indian Recipes,"To make tomato puliogere, first cut the tomato...",https://www.archanaskitchen.com/spicy-tomato-r...,"tomato,salt,chickpea lentils,green chilli,rice...",https://www.archanaskitchen.com/images/archana...,12
2,Ragi Semiya Upma Recipe - Ragi Millet Vermicel...,"1 Onion - sliced,1 teaspoon White Urad Dal (Sp...",50,South Indian Recipes,"To begin making the Ragi Vermicelli Recipe, fi...",https://www.archanaskitchen.com/ragi-vermicell...,"salt,rice vermicelli noodles (thin),asafoetida...",https://www.archanaskitchen.com/images/archana...,12
3,Gongura Chicken Curry Recipe - Andhra Style Go...,"1/2 teaspoon Turmeric powder (Haldi),1 tablesp...",45,Andhra,To begin making Gongura Chicken Curry Recipe f...,https://www.archanaskitchen.com/gongura-chicke...,"tomato,salt,ginger,sorrel leaves (gongura),fen...",https://www.archanaskitchen.com/images/archana...,15
4,Andhra Style Alam Pachadi Recipe - Adrak Chutn...,"oil - as per use, 1 tablespoon coriander seed...",30,Andhra,"To make Andhra Style Alam Pachadi, first heat ...",https://www.archanaskitchen.com/andhra-style-a...,"tomato,salt,ginger,red chillies,curry,asafoeti...",https://www.archanaskitchen.com/images/archana...,12
...,...,...,...,...,...,...,...,...,...
5933,Saffron Paneer Peda Recipe,"2 teaspoons Rose water,1/2 teaspoon Ghee,2 cup...",20,Indian,To begin making the Saffron Paneer Peda recipe...,https://www.archanaskitchen.com/saffron-paneer...,"saffron strands generous,ghee,paneer,rose wate...",https://www.archanaskitchen.com/images/archana...,7
5934,Italian Arancini Rice Balls Recipe With Delici...,"4 sprig Basil leaves - finely chopped,2 cups W...",100,Italian Recipes,To begin making the Italian Arancini Rice Ball...,https://www.archanaskitchen.com/italian-aranci...,"salt,gorgonzola cheese cubes,wheat bread crumb...",https://www.archanaskitchen.com/images/archana...,14
5935,Quinoa Phirnee Recipe (Quinoa Milk Pudding),"3/4 cup Sugar,2 cup Milk - vegans can substitu...",35,Indian,"To begin making Quinoa Phirnee Recipe, place a...",https://www.archanaskitchen.com/quinoa-phirnee...,"ghee,milk,saffron strands,sugar,cardamom powde...",https://www.archanaskitchen.com/images/archana...,8
5936,Ullikadala Pulusu Recipe | Spring Onion Curry,"1 pinch Turmeric powder (Haldi),1/2 teaspoon M...",15,Andhra,To begin making Ullikadala Pulusu Recipe | Spr...,https://www.archanaskitchen.com/ullikadala-pul...,"salt,tamarind water,mustard seeds,asafoetida (...",https://www.archanaskitchen.com/images/archana...,13
5937,Kashmiri Style Kokur Yakhni Recipe-Chicken Coo...,"Salt - as required,3 to 4 Cloves (Laung),Ghee ...",75,Kashmiri,To begin making the Kashmiri Kokur Yakhni reci...,https://www.archanaskitchen.com/kashmiri-kokur...,"black cardamom (badi elaichi),salt,mustard oil...",https://www.archanaskitchen.com/images/archana...,13

In [4]:
print(df.TranslatedInstructions[0])

To begin making the Masala Karela Recipe,de-seed the karela and slice.
Do not remove the skin as the skin has all the nutrients.
Add the karela to the pressure cooker with 3 tablespoon of water, salt and turmeric powder and pressure cook for three whistles.
Release the pressure immediately and open the lids.
Keep aside.Heat oil in a heavy bottomed pan or a kadhai.
Add cumin seeds and let it sizzle.Once the cumin seeds have sizzled, add onions and saute them till it turns golden brown in color.Add the karela, red chilli powder, amchur powder, coriander powder and besan.
Stir to combine the masalas into the karela.Drizzle a little extra oil on the top and mix again.
Cover the pan and simmer Masala Karela stirring occasionally until everything comes together well.
Turn off the heat.Transfer Masala Karela into a serving bowl and serve.Serve Masala Karela along with Panchmel Dal and Phulka for a weekday meal with your family.

In [5]:
text = "To begin making the Masala Karela Recipe,de-seed the karela and slice. Do not remove the skin as the skin has all the nutrients. Add the karela to the pressure cooker with 3 tablespoon of water, salt and turmeric powder and pressure cook for three whistles. Release the pressure immediately and open the lids. Keep aside.Heat oil in a heavy bottomed pan or a kadhai. Add cumin seeds and let it sizzle.Once the cumin seeds have sizzled, add onions and saute them till it turns golden brown in color.Add the karela, red chilli powder, amchur powder, coriander powder and besan. Stir to combine the masalas into the karela.Drizzle a little extra oil on the top and mix again. Cover the pan and simmer Masala Karela stirring occasionally until everything comes together well. Turn off the heat.Transfer Masala Karela into a serving bowl and serve.Serve Masala Karela along with Panchmel Dal and Phulka for a weekday meal with your family."

In [6]:
def preprocess(text):
    text = re.sub(r"[^\w\s']", " ", text)
    text = re.sub(r"[ \n]+", " ", text)
    return text.strip().lower()

In [7]:
preprocess(text)

'to begin making the masala karela recipe de seed the karela and slice do not remove the skin as the skin has all the nutrients add the karela to the pressure cooker with 3 tablespoon of water salt and turmeric powder and pressure cook for three whistles release the pressure immediately and open the lids keep aside heat oil in a heavy bottomed pan or a kadhai add cumin seeds and let it sizzle once the cumin seeds have sizzled add onions and saute them till it turns golden brown in color add the karela red chilli powder amchur powder coriander powder and besan stir to combine the masalas into the karela drizzle a little extra oil on the top and mix again cover the pan and simmer masala karela stirring occasionally until everything comes together well turn off the heat transfer masala karela into a serving bowl and serve serve masala karela along with panchmel dal and phulka for a weekday meal with your family'

In [8]:
df.TranslatedInstructions = df.TranslatedInstructions.map(preprocess)

In [9]:
df

,TranslatedRecipeName,TranslatedIngredients,TotalTimeInMins,Cuisine,TranslatedInstructions,URL,Cleaned-Ingredients,image-url,Ingredient-count
0,Masala Karela Recipe,"1 tablespoon Red Chilli powder,3 tablespoon Gr...",45,Indian,to begin making the masala karela recipe de se...,https://www.archanaskitchen.com/masala-karela-...,"salt,amchur (dry mango powder),karela (bitter ...",https://www.archanaskitchen.com/images/archana...,10
1,Spicy Tomato Rice (Recipe),"2 teaspoon cashew - or peanuts, 1/2 Teaspoon ...",15,South Indian Recipes,to make tomato puliogere first cut the tomatoe...,https://www.archanaskitchen.com/spicy-tomato-r...,"tomato,salt,chickpea lentils,green chilli,rice...",https://www.archanaskitchen.com/images/archana...,12
2,Ragi Semiya Upma Recipe - Ragi Millet Vermicel...,"1 Onion - sliced,1 teaspoon White Urad Dal (Sp...",50,South Indian Recipes,to begin making the ragi vermicelli recipe fir...,https://www.archanaskitchen.com/ragi-vermicell...,"salt,rice vermicelli noodles (thin),asafoetida...",https://www.archanaskitchen.com/images/archana...,12
3,Gongura Chicken Curry Recipe - Andhra Style Go...,"1/2 teaspoon Turmeric powder (Haldi),1 tablesp...",45,Andhra,to begin making gongura chicken curry recipe f...,https://www.archanaskitchen.com/gongura-chicke...,"tomato,salt,ginger,sorrel leaves (gongura),fen...",https://www.archanaskitchen.com/images/archana...,15
4,Andhra Style Alam Pachadi Recipe - Adrak Chutn...,"oil - as per use, 1 tablespoon coriander seed...",30,Andhra,to make andhra style alam pachadi first heat o...,https://www.archanaskitchen.com/andhra-style-a...,"tomato,salt,ginger,red chillies,curry,asafoeti...",https://www.archanaskitchen.com/images/archana...,12
...,...,...,...,...,...,...,...,...,...
5933,Saffron Paneer Peda Recipe,"2 teaspoons Rose water,1/2 teaspoon Ghee,2 cup...",20,Indian,to begin making the saffron paneer peda recipe...,https://www.archanaskitchen.com/saffron-paneer...,"saffron strands generous,ghee,paneer,rose wate...",https://www.archanaskitchen.com/images/archana...,7
5934,Italian Arancini Rice Balls Recipe With Delici...,"4 sprig Basil leaves - finely chopped,2 cups W...",100,Italian Recipes,to begin making the italian arancini rice ball...,https://www.archanaskitchen.com/italian-aranci...,"salt,gorgonzola cheese cubes,wheat bread crumb...",https://www.archanaskitchen.com/images/archana...,14
5935,Quinoa Phirnee Recipe (Quinoa Milk Pudding),"3/4 cup Sugar,2 cup Milk - vegans can substitu...",35,Indian,to begin making quinoa phirnee recipe place a ...,https://www.archanaskitchen.com/quinoa-phirnee...,"ghee,milk,saffron strands,sugar,cardamom powde...",https://www.archanaskitchen.com/images/archana...,8
5936,Ullikadala Pulusu Recipe | Spring Onion Curry,"1 pinch Turmeric powder (Haldi),1/2 teaspoon M...",15,Andhra,to begin making ullikadala pulusu recipe sprin...,https://www.archanaskitchen.com/ullikadala-pul...,"salt,tamarind water,mustard seeds,asafoetida (...",https://www.archanaskitchen.com/images/archana...,13
5937,Kashmiri Style Kokur Yakhni Recipe-Chicken Coo...,"Salt - as required,3 to 4 Cloves (Laung),Ghee ...",75,Kashmiri,to begin making the kashmiri kokur yakhni reci...,https://www.archanaskitchen.com/kashmiri-kokur...,"black cardamom (badi elaichi),salt,mustard oil...",https://www.archanaskitchen.com/images/archana...,13

In [10]:
df.to_csv("food_reciepy.txt", columns = ["TranslatedInstructions"], header=None, index=False)

In [11]:
model = fasttext.train_unsupervised("food_reciepy.txt")

In [12]:
model.get_nearest_neighbors("moong")

[(0.7300874590873718, 'sprouted'),
 (0.6994599103927612, 'dal'),
 (0.6831263303756714, 'sprout'),
 (0.668218731880188, 'mooga'),
 (0.6676380634307861, 'moongphali'),
 (0.6624959111213684, 'moth'),
 (0.6618698835372925, 'sprouts'),
 (0.6338040232658386, 'moolangi'),
 (0.6287908554077148, 'kabila'),
 (0.6089267730712891, 'dalia')]