In [1]:
import pandas as pd
import fasttext
import re

In [2]:
df = pd.read_csv("ecommerce_dataset.csv")

In [3]:
df

          category                                        description
0        Household  Paper Plane Design Framed Wall Hanging Motivat...
1        Household  SAF 'Floral' Framed Painting (Wood, 30 inch x ...
2        Household  SAF 'UV Textured Modern Art Print Framed' Pain...
3        Household  SAF Flower Print Framed Painting (Synthetic, 1...
4        Household  Incredible Gifts India Wooden Happy Birthday U...
...            ...                                                ...
50420  Electronics  Strontium MicroSD Class 10 8GB Memory Card (Bl...
50421  Electronics  CrossBeats Wave Waterproof Bluetooth Wireless ...
50422  Electronics  Karbonn Titanium Wind W4 (White) Karbonn Titan...
50423  Electronics  Samsung Guru FM Plus (SM-B110E/D, Black) Colou...
50424  Electronics                   Micromax Canvas Win W121 (White)

[50425 rows x 2 columns]

In [4]:
df.category.value_counts()

category
Household                 19313
Books                     11820
Electronics               10621
Clothing & Accessories     8671
Name: count, dtype: int64

In [5]:
df.dropna(inplace=True)

In [6]:
df.drop_duplicates(inplace=True)

In [7]:
df

          category                                        description
0        Household  Paper Plane Design Framed Wall Hanging Motivat...
1        Household  SAF 'Floral' Framed Painting (Wood, 30 inch x ...
2        Household  SAF 'UV Textured Modern Art Print Framed' Pain...
3        Household  SAF Flower Print Framed Painting (Synthetic, 1...
4        Household  Incredible Gifts India Wooden Happy Birthday U...
...            ...                                                ...
50402  Electronics  Micromax Bharat 5 Plus Zero impact on visual d...
50403  Electronics  Microsoft Lumia 550 8GB 4G Black Microsoft lum...
50407  Electronics  Microsoft Lumia 535 (Black, 8GB) Colour:Black ...
50408  Electronics  Karbonn Titanium Wind W4 (White) Karbonn Titan...
50410  Electronics  Nokia Lumia 530 (Dual SIM, Grey) Colour:Grey  ...

[27802 rows x 2 columns]

In [8]:
df.category.replace("Clothing & Accessories", "Clothing_Accessories", inplace=True)

C:\Users\Admin\AppData\Local\Temp\ipykernel_12580\2912538940.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df.category.replace("Clothing & Accessories", "Clothing_Accessories", inplace=True)

In [9]:
df.category.unique()

array(['Household', 'Books', 'Clothing_Accessories', 'Electronics'],
      dtype=object)

In [10]:
df["category"] = "__label__" + df["category"].astype(str)

In [11]:
df

                   category                                        description
0        __label__Household  Paper Plane Design Framed Wall Hanging Motivat...
1        __label__Household  SAF 'Floral' Framed Painting (Wood, 30 inch x ...
2        __label__Household  SAF 'UV Textured Modern Art Print Framed' Pain...
3        __label__Household  SAF Flower Print Framed Painting (Synthetic, 1...
4        __label__Household  Incredible Gifts India Wooden Happy Birthday U...
...                     ...                                                ...
50402  __label__Electronics  Micromax Bharat 5 Plus Zero impact on visual d...
50403  __label__Electronics  Microsoft Lumia 550 8GB 4G Black Microsoft lum...
50407  __label__Electronics  Microsoft Lumia 535 (Black, 8GB) Colour:Black ...
50408  __label__Electronics  Karbonn Titanium Wind W4 (White) Karbonn Titan...
50410  __label__Electronics  Nokia Lumia 530 (Dual SIM, Grey) Colour:Grey  ...

[27802 rows x 2 columns]

In [12]:
df["category_description"] = df["category"] + df["description"]

In [13]:
df

,category,description,category_description
0,__label__Household,Paper Plane Design Framed Wall Hanging Motivat...,__label__HouseholdPaper Plane Design Framed Wa...
1,__label__Household,"SAF 'Floral' Framed Painting (Wood, 30 inch x ...",__label__HouseholdSAF 'Floral' Framed Painting...
2,__label__Household,SAF 'UV Textured Modern Art Print Framed' Pain...,__label__HouseholdSAF 'UV Textured Modern Art ...
3,__label__Household,"SAF Flower Print Framed Painting (Synthetic, 1...",__label__HouseholdSAF Flower Print Framed Pain...
4,__label__Household,Incredible Gifts India Wooden Happy Birthday U...,__label__HouseholdIncredible Gifts India Woode...
...,...,...,...
50402,__label__Electronics,Micromax Bharat 5 Plus Zero impact on visual d...,__label__ElectronicsMicromax Bharat 5 Plus Zer...
50403,__label__Electronics,Microsoft Lumia 550 8GB 4G Black Microsoft lum...,__label__ElectronicsMicrosoft Lumia 550 8GB 4G...
50407,__label__Electronics,"Microsoft Lumia 535 (Black, 8GB) Colour:Black ...",__label__ElectronicsMicrosoft Lumia 535 (Black...
50408,__label__Electronics,Karbonn Titanium Wind W4 (White) Karbonn Titan...,__label__ElectronicsKarbonn Titanium Wind W4 (...
50410,__label__Electronics,"Nokia Lumia 530 (Dual SIM, Grey) Colour:Grey ...","__label__ElectronicsNokia Lumia 530 (Dual SIM,..."

In [14]:
df["category_description"][0]

'__label__HouseholdPaper Plane Design Framed Wall Hanging Motivational Office Decor Art Prints (8.7 X 8.7 inch) - Set of 4 Painting made up in synthetic frame with uv textured print which gives multi effects and attracts towards it. This is an special series of paintings which makes your wall very beautiful and gives a royal touch. This painting is ready to hang, you would be proud to possess this unique painting that is a niche apart. We use only the most modern and efficient printing technology on our prints, with only the and inks and precision epson, roland and hp printers. This innovative hd printing technique results in durable and spectacular looking prints of the highest that last a lifetime. We print solely with top-notch 100% inks, to achieve brilliant and true colours. Due to their high level of uv resistance, our prints retain their beautiful colours for many years. Add colour and style to your living space with this digitally printed painting. Some are for pleasure and some for eternal bliss.so bring home this elegant print that is lushed with rich colors that makes it nothing but sheer elegance to be to your friends and family.it would be treasured forever by whoever your lucky recipient is. Liven up your place with these intriguing paintings that are high definition hd graphic digital prints for home, office or any room.'

In [15]:
text = " VIKI's |      Bookcase/Bookshelf    (3-Shelf/Shelve, White)      | ?. hi"

In [16]:
def preprocess(text):
    text = re.sub(r"[^\w\s']", " ", text)
    text = re.sub(r" +", " ", text)
    return text.strip().lower()

In [17]:
preprocess(text)

"viki's bookcase bookshelf 3 shelf shelve white hi"

In [18]:
df["category_description"] = df["category_description"].map(preprocess)

In [19]:
df

,category,description,category_description
0,__label__Household,Paper Plane Design Framed Wall Hanging Motivat...,__label__householdpaper plane design framed wa...
1,__label__Household,"SAF 'Floral' Framed Painting (Wood, 30 inch x ...",__label__householdsaf 'floral' framed painting...
2,__label__Household,SAF 'UV Textured Modern Art Print Framed' Pain...,__label__householdsaf 'uv textured modern art ...
3,__label__Household,"SAF Flower Print Framed Painting (Synthetic, 1...",__label__householdsaf flower print framed pain...
4,__label__Household,Incredible Gifts India Wooden Happy Birthday U...,__label__householdincredible gifts india woode...
...,...,...,...
50402,__label__Electronics,Micromax Bharat 5 Plus Zero impact on visual d...,__label__electronicsmicromax bharat 5 plus zer...
50403,__label__Electronics,Microsoft Lumia 550 8GB 4G Black Microsoft lum...,__label__electronicsmicrosoft lumia 550 8gb 4g...
50407,__label__Electronics,"Microsoft Lumia 535 (Black, 8GB) Colour:Black ...",__label__electronicsmicrosoft lumia 535 black ...
50408,__label__Electronics,Karbonn Titanium Wind W4 (White) Karbonn Titan...,__label__electronicskarbonn titanium wind w4 w...
50410,__label__Electronics,"Nokia Lumia 530 (Dual SIM, Grey) Colour:Grey ...",__label__electronicsnokia lumia 530 dual sim g...

In [20]:
from sklearn.model_selection import train_test_split

In [21]:
train, test = train_test_split(df, test_size=0.2)

In [22]:
train.shape, test.shape

((22241, 3), (5561, 3))

In [23]:
train.to_csv("ecommerce.train", columns = ["category_description"], index = False, header=False)
test.to_csv("ecommerce.test", columns = ["category_description"], index = False, header=False)

In [24]:
model = fasttext.train_supervised(input = "ecommerce.train")
model.test("ecommerce.test")

(4401, 0.0406725744149057, 0.0406725744149057)

In [25]:
model.predict("wintech assemble desktop pc cpu 500 gb sata hdd 4 gb ram intel 2d processor")

(('__label__electronicsamazonbasics',), array([0.00044217]))

In [26]:
model.predict("think and grow ricvh delux edition")

(('__label__booksthe',), array([0.02714723]))

In [27]:
model.get_nearest_neighbors("painting")

[(0.3714521527290344, 'mince'),
 (0.3550081253051758, 'wellness'),
 (0.3512783646583557, "brown's"),
 (0.3320092260837555, 'regimen'),
 (0.32310330867767334, 'stations'),
 (0.3195095956325531, 'colorless'),
 (0.31262490153312683, 'futura'),
 (0.3124983310699463, 'ownership'),
 (0.3120347261428833, 'gurcharan'),
 (0.30964842438697815, 'landlord')]

In [28]:
model.get_nearest_neighbors("sony")

[(0.9759612679481506, '22khz'),
 (0.9758082032203674, 'lessen'),
 (0.9757312536239624, 'stowed'),
 (0.975696325302124, '210mm'),
 (0.9756470918655396, 'c1'),
 (0.975622296333313, 'compressing'),
 (0.9755293130874634, 'erased'),
 (0.9754757285118103, 'eg5'),
 (0.9754404425621033, '480gb'),
 (0.975439190864563, 'mpeg2')]